test

diff --git a/test/devsecops-cicd-containers-main/buildspec-snyk.yml b/test/devsecops-cicd-containers-main/buildspec-snyk.yml
--- a/test/devsecops-cicd-containers-main/buildspec-snyk.yml
+++ b/test/devsecops-cicd-containers-main/buildspec-snyk.yml
@@ -43,17 +43,17 @@ phases:
         \"build_id\": env.CODEBUILD_BUILD_ID, \
         \"source_commitid\": env.CODEBUILD_RESOLVED_SOURCE_VERSION, \
         \"report\": . }" snyk-results.json > payload.json
-      - cat payload.json
+      # - cat payload.json
       - echo ""
-      # - |
-      #   if (grep -E 'high|critical' payload.json); then 
-      #     aws lambda invoke --function-name ImpToSecurityHubEKS --payload file://payload.json snyk-results.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
-      #     echo "There are critical or high vulnerabilities.. failing the build"
-      #     exit 1;
-      #   elif (grep -E 'medium|low' payload.json); then
-      #     aws lambda invoke --function-name ImpToSecurityHubEKS --payload file://payload.json snyk-results.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
-      #   fi
-      # - printf '[{"name":"hello-k8s","imageUri":"%s"}]' testing:$TAG > build.json
+      - |
+        if (grep -E 'high|critical' payload.json); then 
+          aws lambda invoke --function-name ImpToSecurityHubEKS --payload file://payload.json snyk-results.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+          echo "There are critical or high vulnerabilities.. failing the build"
+          exit 1;
+        elif (grep -E 'medium|low' payload.json); then
+          aws lambda invoke --function-name ImpToSecurityHubEKS --payload file://payload.json snyk-results.json && echo "LAMBDA_SUCCEDED" || echo "LAMBDA_FAILED";
+        fi
+      - printf '[{"name":"hello-k8s","imageUri":"%s"}]' testing:$TAG > build.json
 artifacts:
   type: zip
   files: '**/*'
